### ISSUE TITLE
Workflow failed with 422 Error

### ISSUE THREAD

**Issue by Wattyyy** [reviewdog/action-eslint#143]
I ran into a 422 error when I tried to post review comments by reviewdog/action-eslint@v1.
I would appreciate it if anyone could give me a solution.

## Error Code
The owner's name and repository's name are replaced.
```
reviewdog: POST https://api.github.com/repos/{owner}/{repo}/pulls/183/reviews: 422 Unprocessable Entity [{Resource: Field: Code: Message:Pull request review thread path is invalid and Pull request review thread diff hunk can't be blank}]
[148](https://github.com/{owner}/{repo}/runs/6634777903?check_suite_focus=true#step:5:151)
  ::endgroup::
[149](https://github.com/{owner}/{repo}/runs/6634777903?check_suite_focus=true#step:5:153)
Error: Process completed with exit code 1.
```

## Configuration
I configured yml file as following.

```yml
name: reviewdog
on: 
  pull_request:
    branches:
      - "release"
jobs:
  eslint:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13"
      - run: npm install
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
```
