### ISSUE TITLE
reviewdog: This GitHub token doesn't have write permission of Review API [1]

### ISSUE THREAD

**Issue by Inrixia** [reviewdog/action-eslint#148]
So I'm following the example provided and everything is working except for the given error above...

```yaml
 eslint:
  name: eslint
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: reviewdog/action-eslint@v1
     with:
      reporter: github-check
      eslint_flags: "src/"
```
