### ISSUE TITLE
support npm v9

### ISSUE THREAD

**Issue by yshrsmz** [reviewdog/action-eslint#152]
https://github.com/npm/cli/blob/latest/CHANGELOG.md#features-8
https://github.com/npm/statusboard/issues/537

npm v9 removes `bin` command which this action uses.

action output:

```
🐶 Installing reviewdog ... https://github.com/reviewdog/reviewdog
 Running `npm install` to install eslint ...
/home/runner/work/_actions/reviewdog/action-eslint/v1/script.sh: 20: Unknown: not found
eslint version:
 Running eslint with reviewdog 🐶 ...
Error: Process completed with exit code 1.
```

**Comment by yshrsmz** [comment]
Should we simply use npx?

**Comment by rpellerin** [comment]
With NodeJS 19.3 being out now, supporting npm v9 would be much appreciated :blush:

**Comment by Djiit** [comment]
Hey team, really looking forward using this feature. How can we help ?

**Comment by yshrsmz** [comment]
https://docs.npmjs.com/cli/v7/commands/npm-exec

`npm exec --offline eslint .` or `npx --offline eslint .` fails if no eslint binary exists locally, so we could first use either of these commands, and if it fails then calling `npm install` and retry.

**Comment by mpowell90** [comment]
Just ran into this issue. A workaround is to target `node-version: 16`, which bundles an older version on npm until v9 support is added.

**Comment by remnantkevin** [comment]
> Just ran into this issue. A workaround is to target `node-version: 16`, which bundles an older version on npm until v9 support is added.

@mpowell90 Thanks for the suggested workaround 👍 

Where I work we had set the `node-version` to `18` for `actions/setup-node@v3`. Last week, `18` was resolving to `18.13` in our workflow runs, while this week it resolved to `18.14`. According to the [Node.js releases page](https://nodejs.org/en/download/releases/), `18.13` comes bundled with npm v8, while `18.14` comes bundled with npm v9. So for now we have pinned the minor version of node to ensure we're using npm v8:
```yaml
      - uses: actions/setup-node@v3
         with:
           node-version: '18.13'
           cache: 'yarn'
```

**Comment by melibe23** [comment]
I am not able to workaround this. Can someone help me?

This is my yml

```
name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install --legacy-peer-deps --force
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: 'cypress/'
          github_token: ${{ secrets.REVIEW_DOG_TOKEN }}
          level: warning

```

**Comment by melibe23** [comment]
I fixed it like this:

```
name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18.13'
      - run: npm install
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: 'cypress/'
          github_token: ${{ secrets.REVIEW_DOG_TOKEN }}
          level: warning

```
