### ISSUE TITLE
How do you use this action in a folder not in the root directory?

### ISSUE THREAD

**Issue by ChadTaljaardt** [reviewdog/action-eslint#18]
Hello, 

I am new to working with Github actions. 

I am trying to run this action on a "user_interface" sub directory, can anyone explain to me how to do this?

Thanks!

**Comment by jiro4989** [comment]
@ChadTaljaardt 

1. Please try to put this YAML file to `.github/workflows/reviewdog.yml` .

```
name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'user_interface/' # <-- Target source directory
```

2. Create a new branch
3. Add your source code
4. Create a pull request
5. See pull request, or github actions (`https://github.com/<your_name>/<your_repo>/actions`)

See also:

* [README](https://github.com/reviewdog/action-eslint#githubworkflowsreviewdogyml)
