### ISSUE TITLE
Error when running in scheduled action

### ISSUE THREAD

**Issue by bakkerthehacker** [reviewdog/action-eslint#41]
When running in a scheduled github job, this action fails with the error:

`reviewdog: post failed for eslint: failed to create check: POST https://api.github.com/repos///check-runs: 404 Not Found []`

```yaml
on:
  push:
  schedule:
    # Every day at midnight
    - cron: '0 0 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: reviewdog/action-eslint@v1
      with:
        reporter: github-check
        fail_on_error: true
```

The push version works fine but the scheduled version fails.
