### ISSUE TITLE
The fail_on_error isn't recognize

### ISSUE THREAD

**Issue by ebiton-eig** [reviewdog/action-eslint#42]
The fail_on_error isn't recognize :

```yaml
      - name: Run eslint with reviewdog
        uses: reviewdog/action-eslint@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: warning
          fail_on_error: true
          reporter: github-pr-review
          eslint_flags: 'src/'
```

`Warning: Unexpected input(s) 'fail_on_error', valid inputs are ['entryPoint', 'args', 'github_token', 'level', 'reporter', 'eslint_flags']`
