### ISSUE TITLE
fail_on_error works with lint warnings

### ISSUE THREAD

**Issue by sa9sha9** [reviewdog/action-eslint#62]
I guess it should work only with lint **errors**.  Is it possible to fail only on error?

My `reviewdog.yml` is below.
```yml
name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          workdir: "app/"
          eslint_flags: "--cache --ext .js,.jsx,.ts,.tsx ."
          level: error
          fail_on_error: true
```
