### ISSUE TITLE
Action only outputs eslint version 

### ISSUE THREAD

**Issue by adrianthedev** [reviewdog/action-eslint#65]
I have the following (pretty much standard) config in a (pretty much standard) laravel app (all the js is in `./resources/js`.

After the action finishes the `npm install` the only output I see is eslint version number. 
I tried the following: 
 - using `--config` instead of `-c` eslint flag, no luck.
 - remove all flags except the directory `resources/js/`, no luck.
 - ran it manually `$(npm bin)/eslint -c .eslintrc.json --ext .js,.vue resources/js` (it outputs the errors)

```yml
name: Reviewdog

on: [pull_request]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: '-c .eslintrc.json --ext .js,.vue resources/js/'
```

![image](https://user-images.githubusercontent.com/1334409/102341555-acb82a80-3fa0-11eb-97fc-dc50e4aa9dba.png)
