### ISSUE TITLE
fail_on_error flag is not working as expected

### ISSUE THREAD

**Issue by dmchandru** [reviewdog/action-eslint#73]
My workflow config file as follows
```
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review # Change reporter.
          workdir: 'src/'
          fail_on_error: true
```
Initially the runner was reported the status check as failed if the PR code have any lint issues. But now the status check seems to passed even if the code have lint issues.
